### ISSUE TITLE
Have mirrored MC-10

### ISSUE THREAD

**Issue by jggames** [mtinnes/mc-10#7]
Dear Mike,

I have mirrored your emulator to my faculty website at Cape Breton University:
http://faculty.cbu.ca/jgerrie/MC10/

Modified the main menu to list a bunch of classic (1972-1982) Basic programs. I want to introduce my students (history of computing class) to some of these old but influential programs and want it to be as simple as possible for them.

Have changed the font to be more like the original MC-10 too (just preference thing).

Hope this is okay under GNU.  Let me know if it's not or if there is anything else I should do.

JIm Gerrie

**Comment by mtinnes** [comment]
Not a problem Jim, happy to help you out.
